version = 0.1

[default.deploy.parameters]
stack_name = "customer-id-api-dev"
resolve_s3 = true
s3_prefix = "customer-id-api-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
